### ISSUE TITLE
Tạo câu hỏi thứ 3 cho màn 2

### ISSUE THREAD

**Issue by hongthamuet** [hongthamuet/Substract-using-10#16]
Cũng tương tự như các câu hỏi 1, 2 cần tạo các câu hỏi gợi ý để trả lời câu hỏi .

**Comment by lxhuy193** [comment]
ok nhé, mình sẽ làm ngay đây

**Comment by lxhuy193** [comment]
mình đã hoàn thành xong!

**Comment by hongthamuet** [comment]
OK.
